version: '3.7'


services:
  db:
    container_name: db_whitebird
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./.env

  web:
    container_name: whitebird_web
    restart: always
    build:
      context: .
    volumes:
        - ./static/:/static
        - ./media/:/media
        - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - db

  nginx:
    container_name: nginx_barter
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
      - ./media/:/media
    networks:
      - my-network
    depends_on:
      - db
      - web

volumes:
  postgres_data:
  media:
  static:

networks:
  my-network: