# Generated by Django 4.1.7 on 2023-04-18 17:37

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_options_alter_video_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="compressed_video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="video_compressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
