# Generated by Django 4.1.7 on 2023-04-26 20:37

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.videos.models.generate_filename,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(max_length=255, upload_to="videos/"),
        ),
    ]
