# Generated by Django 4.1.7 on 2023-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_img"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Анонсы", "verbose_name_plural": "Анонсы"},
        ),
    ]
